#!/usr/bin/env python
"""
Generate Connect IQ bitmap fonts (.fnt + .png) from TrueType fonts, per resolution.

Connect IQ's <font> resource consumes an AngelCode BMFont (text .fnt) plus a PNG
glyph atlas - it cannot rasterize a .ttf at build time, and bitmap fonts do NOT
scale. So we bake a separate set for each panel size and let monkey.jungle pick the
right one via device resourcePath. The base 454 set lives in resources/fonts; every
other distinct panel size used by a product in manifest.xml gets an override folder
(see TARGETS below). Fonts scale by min(width, height) / 454; only round panels are
targeted (square/rectangular Venu Sq 2 / Venu X1 are excluded).

Glyphs are rendered white with coverage in the alpha channel so dc.setColor() tints
the text. Sizes are defined at the 454 base and scaled to each target.

Run:  python tools/gen_fonts.py
"""
import os
from PIL import Image, ImageFont, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "fonts-src")
PAD = 2  # transparent padding between glyphs to avoid bleed

DIGITS = "0123456789"
ALPHA = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

BASE_RES = 454
# Base (454) sizes; scaled per target resolution below.
FONTS = [
    {"name": "exocet_time",  "ttf": "RoundedTime.ttf", "size": 90, "chars": DIGITS + ":"},
    {"name": "exocet_value", "ttf": "SegoeUILight.ttf", "size": 36, "chars": DIGITS + "%-"},
    {"name": "exocet_label", "ttf": "SegoeUILight.ttf", "size": 24, "chars": ALPHA + DIGITS + " ,.:%|-•°"},
]

# Each target panel (width, height) and where its font set lives. Fonts are scaled
# by min(w, h) / 454 so they fit the shorter axis on non-square (rectangular) panels.
# 454x454 is the base set in resources/fonts; every other distinct panel size used by
# a product in manifest.xml gets its own override folder, selected in monkey.jungle.
TARGETS = [
    (454, 454, "resources/fonts"),                  # fenix8 47/51mm, Pro, fr965/970, venu3/445, epix2pro51, fr57047, approachs7047, d2mach2, descentmk351
    (416, 416, "resources-round-416x416/fonts"),    # fenix8 43mm, fr265, fenixe, epix2, epix2pro47, venu2/2plus, d2airx10/mach1, instinct3amoled50
    (390, 390, "resources-round-390x390/fonts"),    # fr165, fr57042, epix2pro42, venu3s/441, vivoactive5/6, instinct3amoled45/crossover, marq2, approachs50/7042, descentg2/mk343
    (360, 360, "resources-round-360x360/fonts"),    # fr265s, venu2s
    (280, 280, "resources-round-280x280/fonts"),    # fenix7x(pro), fenix8solar51, enduro3
    (260, 260, "resources-round-260x260/fonts"),    # fr255(m), fr955, fenix7(pro), fenix8solar47
    (240, 240, "resources-round-240x240/fonts"),    # fenix7s(pro)
    (218, 218, "resources-round-218x218/fonts"),    # fr255s(m)
    (176, 176, "resources-round-176x176/fonts"),    # instinct3solar45, instincte45
    (166, 166, "resources-round-166x166/fonts"),    # instincte40
]

FONTS_XML = (
    '<resources>\n'
    '    <!-- Exocet bitmap fonts, generated by tools/gen_fonts.py for this panel size. -->\n'
    '    <fonts>\n'
    '        <font id="ExocetTime"  filename="exocet_time.fnt"  antialias="true" />\n'
    '        <font id="ExocetValue" filename="exocet_value.fnt" antialias="true" />\n'
    '        <font id="ExocetLabel" filename="exocet_label.fnt" antialias="true" />\n'
    '    </fonts>\n'
    '</resources>\n'
)


def next_pow2(n):
    p = 1
    while p < n:
        p <<= 1
    return p


def gen(spec, size, outdir):
    font = ImageFont.truetype(os.path.join(SRC, spec["ttf"]), size)
    ascent, descent = font.getmetrics()
    line_height = ascent + descent

    glyphs = []
    for ch in spec["chars"]:
        l, t, r, b = font.getbbox(ch)
        glyphs.append({"ch": ch, "l": l, "t": t, "w": max(r - l, 0), "h": max(b - t, 0),
                       "adv": int(round(font.getlength(ch)))})

    max_w = max((g["w"] for g in glyphs), default=1)
    atlas_w = next_pow2(max(128, max_w + PAD * 2))
    x, y, row_h = PAD, PAD, 0
    for g in glyphs:
        if x + g["w"] + PAD > atlas_w:
            x = PAD
            y += row_h + PAD
            row_h = 0
        g["x"], g["y"] = x, y
        x += g["w"] + PAD
        row_h = max(row_h, g["h"])
    atlas_h = next_pow2(y + row_h + PAD)

    atlas = Image.new("RGBA", (atlas_w, atlas_h), (255, 255, 255, 0))
    for g in glyphs:
        if g["w"] == 0 or g["h"] == 0:
            continue
        cell = Image.new("L", (g["w"], g["h"]), 0)
        ImageDraw.Draw(cell).text((-g["l"], -g["t"]), g["ch"], font=font, fill=255)
        white = Image.new("RGBA", (g["w"], g["h"]), (255, 255, 255, 0))
        white.putalpha(cell)
        atlas.alpha_composite(white, (g["x"], g["y"]))

    png_name = spec["name"] + ".png"
    atlas.save(os.path.join(outdir, png_name))

    lines = [
        'info face="%s" size=%d bold=0 italic=0 charset="" unicode=1 stretchH=100 '
        'smooth=1 aa=1 padding=0,0,0,0 spacing=1,1 outline=0' % (spec["name"], size),
        "common lineHeight=%d base=%d scaleW=%d scaleH=%d pages=1 packed=0 "
        "alphaChnl=1 redChnl=4 greenChnl=4 blueChnl=4" % (line_height, ascent, atlas_w, atlas_h),
        'page id=0 file="%s"' % png_name,
        "chars count=%d" % len(glyphs),
    ]
    for g in glyphs:
        lines.append(
            "char id=%d x=%d y=%d width=%d height=%d xoffset=%d yoffset=%d "
            "xadvance=%d page=0 chnl=15"
            % (ord(g["ch"]), g["x"], g["y"], g["w"], g["h"], g["l"], g["t"], g["adv"]))
    lines.append("kernings count=0")
    with open(os.path.join(outdir, spec["name"] + ".fnt"), "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    return size, atlas_w, atlas_h


if __name__ == "__main__":
    for w, h, reldir in TARGETS:
        outdir = os.path.join(ROOT, reldir)
        os.makedirs(outdir, exist_ok=True)
        scale = min(w, h) / float(BASE_RES)
        print("== %dx%d -> %s ==" % (w, h, reldir))
        for spec in FONTS:
            size = max(8, int(round(spec["size"] * scale)))
            s, aw, ah = gen(spec, size, outdir)
            print("   %-13s size=%d atlas=%dx%d" % (spec["name"], s, aw, ah))
        with open(os.path.join(outdir, "fonts.xml"), "w", newline="\n") as f:
            f.write(FONTS_XML)
    print("Done.")
